from __future__ import annotations

# Audio framing and collector geometry.
FRAME_LENGTH = 2048
HOP_LENGTH = 256
TEMPO_ESTIMATION_HOP_LENGTH = 1024
RMS_MEDIAN_THRESHOLD_MAX_PEAK_RATIO = 0.45
NESTED_SEGMENT_DEDUP_MAX_START_DELTA = 0.02
CROSS_COLLECTOR_DEDUP_MIN_OVERLAP_RATIO = 0.5
SEGMENT_OVERLAP_TRIM_MAX_OVERLAP = 0.18
SEGMENT_OVERLAP_TRIM_MIN_DURATION = 0.18
MULTI_ONSET_GAP_MIN_DURATION = 1.0
MULTI_ONSET_GAP_MIN_EDGE_SPACING = 0.18
MULTI_ONSET_GAP_MIN_INTERVAL = 0.18
MULTI_ONSET_GAP_MAX_INTERVAL = 0.42
MULTI_ONSET_GAP_MIN_SHORT_INTERVALS = 2
GAP_RUN_LEAD_IN_MIN_FOLLOWUP_GAP = 0.9
SPARSE_GAP_TAIL_MIN_DURATION = 1.0
SPARSE_GAP_TAIL_MIN_PREVIOUS_EDGE = 0.04
SPARSE_GAP_TAIL_MAX_ONSET_OFFSET = 0.45
SPARSE_GAP_TAIL_MIN_TRAILING_EDGE = 0.6
SPARSE_GAP_TAIL_MIN_INTERVAL = 0.08
SPARSE_GAP_TAIL_MAX_INTERVAL = 0.45
SPARSE_GAP_TAIL_SEGMENT_DURATION = 0.24
SHORT_BRIDGE_ACTIVE_RANGE_MAX_DURATION = 0.16
SHORT_BRIDGE_ACTIVE_RANGE_MAX_ONSET_OFFSET = 0.03
SHORT_BRIDGE_ACTIVE_RANGE_MIN_NEXT_ONSET_GAP = 0.1
SHORT_BRIDGE_ACTIVE_RANGE_MAX_NEXT_ONSET_GAP = 0.3
SHORT_BRIDGE_ACTIVE_RANGE_MIN_NEXT_EDGE_GAP = 0.08
SHORT_BRIDGE_ACTIVE_RANGE_MAX_NEXT_EDGE_GAP = 0.2

# Gap-head collectors.
ACTIVE_RANGE_START_CLUSTER_MIN_GAP = 0.45
ACTIVE_RANGE_START_CLUSTER_MAX_SPAN = 0.09
ACTIVE_RANGE_START_CLUSTER_MAX_DURATION = 0.35
LONG_RANGE_BACKTRACK_MIN_DURATION = 0.35
CLUSTERED_RANGE_HEAD_MIN_DURATION = 0.05
ACTIVE_RANGE_HEAD_CLUSTER_MAX_OFFSET = 0.3
ACTIVE_RANGE_HEAD_CLUSTER_MAX_INTERVAL = 0.14
ACTIVE_RANGE_HEAD_CLUSTER_MIN_DURATION = 0.35

# Onset attack analysis and gate thresholds.
ATTACK_ANALYSIS_SECONDS = 0.16
ATTACK_ANALYSIS_RATIO = 0.35
ONSET_ENERGY_WINDOW_SECONDS = 0.08
SPECTRAL_FLUX_HIGH_BAND_MIN_FREQUENCY = 2000.0
ONSET_ATTACK_MIN_BROADBAND_GAIN = 10.0
ONSET_ATTACK_MIN_HIGH_BAND_FLUX = 1.5
ONSET_ATTACK_GAIN_REQUIRES_MIN_FLUX = 0.5
ONSET_ATTACK_MODERATE_GAIN = 3.0
ONSET_ATTACK_MODERATE_GAIN_MIN_FLUX = 0.8
ATTACK_VALIDATED_GAP_SEGMENT_DURATION = 0.24
ATTACK_REFINED_ONSET_MAX_INTERVAL = 0.15

# Residual-decay and recent-primary replacement thresholds.
MIN_RECENT_NOTE_ONSET_GAIN = 2.5
RESIDUAL_DECAY_MIN_ONSET_GAIN = 1.5
RECENT_PRIMARY_REPLACEMENT_MIN_SCORE_RATIO = 0.18
RECENT_PRIMARY_REPLACEMENT_MIN_FUNDAMENTAL_RATIO = 0.6
RECENT_PRIMARY_REPLACEMENT_RELAXED_FUNDAMENTAL_RATIO = 0.45
RECENT_PRIMARY_REPLACEMENT_STRONG_ONSET_GAIN = 100.0
RECENT_PRIMARY_REPLACEMENT_MIN_ONSET_GAIN = 20.0
RECENT_PRIMARY_REPLACEMENT_MIN_ONSET_RATIO = 8.0
RECENT_PRIMARY_REPLACEMENT_MAX_DURATION = 0.47
DESCENDING_REPEATED_PRIMARY_MAX_DURATION = 0.47
DESCENDING_REPEATED_PRIMARY_MAX_PRIMARY_ONSET_GAIN = 2.5
DESCENDING_REPEATED_PRIMARY_MIN_REPLACEMENT_ONSET_GAIN = 5.0
DESCENDING_REPEATED_PRIMARY_MIN_REPLACEMENT_ONSET_RATIO = 4.0
DESCENDING_REPEATED_PRIMARY_MIN_SCORE_RATIO = 0.35
DESCENDING_REPEATED_PRIMARY_MIN_FUNDAMENTAL_RATIO = 0.9
DESCENDING_REPEATED_PRIMARY_MIN_INTERVAL_CENTS = 80.0
DESCENDING_REPEATED_PRIMARY_MAX_INTERVAL_CENTS = 220.0

# Secondary promotion heuristics.
RECENT_UPPER_SECONDARY_MIN_DURATION = 0.22
RECENT_UPPER_SECONDARY_PRIMARY_ONSET_GAIN = 20.0
UPPER_SECONDARY_WEAK_ONSET_MIN_DURATION = 0.4
UPPER_SECONDARY_WEAK_ONSET_MAX_GAIN = 30.0
UPPER_SECONDARY_WEAK_ONSET_SCORE_RATIO = 0.14
SHORT_SECONDARY_WEAK_ONSET_MAX_DURATION = 0.36
SHORT_SECONDARY_WEAK_ONSET_MIN_PRIMARY_GAIN = 15.0
SHORT_SECONDARY_WEAK_ONSET_MAX_GAIN = 2.5
SHORT_SECONDARY_WEAK_ONSET_MAX_RATIO = 0.08
SHORT_SECONDARY_WEAK_ONSET_SCORE_RATIO = 0.55
LOWER_SECONDARY_WEAK_ONSET_MAX_DURATION = 0.45
LOWER_SECONDARY_WEAK_ONSET_MIN_PRIMARY_GAIN = 20.0
LOWER_SECONDARY_WEAK_ONSET_MAX_GAIN = 2.5
LOWER_SECONDARY_WEAK_ONSET_MAX_RATIO = 0.08
LOWER_SECONDARY_WEAK_ONSET_SCORE_RATIO = 0.35
LOWER_SECONDARY_OCTAVE_PROMOTION_MAX_DURATION = 0.32
STALE_PRIMARY_UPPER_OCTAVE_PROMOTION_MAX_DURATION = 0.12
STALE_PRIMARY_UPPER_OCTAVE_PROMOTION_MAX_PRIMARY_ONSET_GAIN = 1.5
STALE_PRIMARY_UPPER_OCTAVE_PROMOTION_MAX_PRIMARY_FUNDAMENTAL_RATIO = 0.85
STALE_PRIMARY_UPPER_OCTAVE_PROMOTION_MIN_UPPER_FUNDAMENTAL_RATIO = 0.95
STALE_PRIMARY_UPPER_OCTAVE_PROMOTION_MIN_UPPER_SCORE_RATIO = 0.25
STALE_PRIMARY_UPPER_OCTAVE_PROMOTION_MIN_UPPER_ALIAS_RATIO = 1.2
STALE_PRIMARY_UPPER_OCTAVE_PROMOTION_MIN_SUPPORTING_SCORE_RATIO = 0.75
STALE_PRIMARY_UPPER_OCTAVE_PROMOTION_MIN_SCORE = 121.0
RECENT_UPPER_OCTAVE_ALIAS_PROMOTION_MAX_DURATION = 0.35
RECENT_UPPER_OCTAVE_ALIAS_PROMOTION_MAX_PRIMARY_FUNDAMENTAL_RATIO = 0.7
RECENT_UPPER_OCTAVE_ALIAS_PROMOTION_MIN_UPPER_FUNDAMENTAL_RATIO = 0.95
RECENT_UPPER_OCTAVE_ALIAS_PROMOTION_MIN_UPPER_ALIAS_RATIO = 0.8
RECENT_UPPER_OCTAVE_ALIAS_PROMOTION_MIN_UPPER_SCORE_RATIO = 0.7
RECENT_UPPER_OCTAVE_ALIAS_PROMOTION_MIN_SUPPORTING_LOWER_SCORE_RATIO = 0.45
LOWER_SECONDARY_OCTAVE_PROMOTION_MAX_LOWER_SCORE_RATIO = 0.4
LOWER_SECONDARY_OCTAVE_PROMOTION_MAX_LOWER_FUNDAMENTAL_RATIO = 0.85
LOWER_SECONDARY_OCTAVE_PROMOTION_MIN_UPPER_FUNDAMENTAL_RATIO = 0.94
LOWER_SECONDARY_OCTAVE_PROMOTION_MIN_UPPER_SCORE_RATIO = 0.15
LOWER_SECONDARY_OCTAVE_PROMOTION_MIN_PRIMARY_SCORE_RATIO = 0.04
LOWER_SECONDARY_OCTAVE_PROMOTION_MIN_FUNDAMENTAL_RATIO_DELTA = 0.12
LOWER_SECONDARY_OCTAVE_PROMOTION_MIN_PRIMARY_INTERVAL_CENTS = 1000.0
LOWER_SECONDARY_OCTAVE_PROMOTION_MAX_PRIMARY_INTERVAL_CENTS = 700.0

# Primary-run and suffix heuristics.
ASCENDING_PRIMARY_RUN_MIN_LENGTH = 3
ASCENDING_PRIMARY_RUN_MAX_DURATION = 0.45
ASCENDING_PRIMARY_RUN_SECONDARY_SCORE_RATIO = 0.35
ASCENDING_PRIMARY_RUN_RECENT_SECONDARY_ONSET_GAIN = 8.0
DESCENDING_PRIMARY_SUFFIX_MIN_LENGTH = 2
DESCENDING_PRIMARY_SUFFIX_MAX_DURATION = 0.5
DESCENDING_PRIMARY_SUFFIX_PRIMARY_ONSET_GAIN = 10.0
DESCENDING_PRIMARY_SUFFIX_UPPER_SCORE_RATIO = 0.6
DESCENDING_REPEATED_PRIMARY_STALE_UPPER_MAX_ONSET_GAIN = 1.5
DESCENDING_REPEATED_PRIMARY_STALE_UPPER_SCORE_RATIO = 0.95
ADJACENT_SEPARATED_DYAD_MAX_DURATION = 0.6
ADJACENT_SEPARATED_DYAD_RUN_MIN_FORWARD_SUPPORT = 2
PRIOR_ONSET_BACKTRACK_SECONDS = 0.55

# Harmonic scoring and repeated-pattern suppression.
HARMONIC_WEIGHTS = [1.0, 0.55, 0.3, 0.15]
HARMONIC_BAND_CENTS = 40.0
SUPPRESSION_BAND_CENTS = 45.0
MAX_POLYPHONY = 4
PRIMARY_REJECTION_MAX_SCORE = 30.0
PRIMARY_REJECTION_MAX_FUNDAMENTAL_RATIO = 0.97
TERTIARY_MIN_SCORE_RATIO = 0.12
TERTIARY_MIN_FUNDAMENTAL_RATIO = 0.85
TERTIARY_MIN_SCORE = 20.0
ITERATIVE_TERTIARY_OCTAVE_MIN_FUNDAMENTAL_RATIO = 0.55
ITERATIVE_RESCUE_MIN_FUNDAMENTAL_RATIO = 0.9
TERTIARY_MIN_ONSET_GAIN = 1.8
TERTIARY_BACKWARD_LOOKBACK_SECONDS = 0.2
TERTIARY_MIN_BACKWARD_ATTACK_GAIN = 20.0
TERTIARY_BACKWARD_GATE_ONSET_OVERRIDE = 20.0
SEMITONE_LEAKAGE_MAX_CENTS = 150.0
SEMITONE_LEAKAGE_MAX_SCORE_RATIO = 0.20
GLISS_CLUSTER_MAX_GAP = 0.06
GLISS_CLUSTER_MAX_EVENT_DURATION = 0.85
GLISS_CLUSTER_MAX_TOTAL_DURATION = 1.2
GLISS_CLUSTER_TARGET_NOTE_COUNT = 3
GLISS_LEADING_SUBSET_MAX_DURATION = 0.18
GLISS_LEADING_SUBSET_SCORE_RATIO = 4.0
GLISS_TERTIARY_MAX_DURATION = 1.35
GLISS_TERTIARY_SCORE_RATIO = 0.02
GLISS_TERTIARY_MIN_SCORE = 20.0
GLISS_TERTIARY_STRONG_ONSET_GAIN = 5.0
GLISS_TERTIARY_WEAK_ONSET_GAIN = 2.0
GLISS_TERTIARY_MIN_FUNDAMENTAL_RATIO = 0.9
LOWER_MIXED_ROLL_EXTENSION_MAX_DURATION = 1.25
LOWER_MIXED_ROLL_EXTENSION_MIN_EXTENSION_SCORE_RATIO = 0.35
LOWER_MIXED_ROLL_EXTENSION_MIN_UPPER_SCORE_RATIO = 0.4
LOWER_MIXED_ROLL_EXTENSION_MIN_FUNDAMENTAL_RATIO = 0.97
LOWER_MIXED_ROLL_EXTENSION_MIN_PRIMARY_ONSET_GAIN = 25.0
LOWER_MIXED_ROLL_EXTENSION_MIN_EXTENSION_ONSET_GAIN = 20.0
LOWER_ROLL_TAIL_EXTENSION_MAX_DURATION = 0.4
LOWER_ROLL_TAIL_EXTENSION_MIN_FUNDAMENTAL_RATIO = 0.95
LOWER_ROLL_TAIL_EXTENSION_MIN_PRIMARY_ONSET_GAIN = 25.0
LOWER_ROLL_TAIL_EXTENSION_MAX_ONSET_GAIN = 5.0
LOWER_ROLL_TAIL_EXTENSION_MIN_SCORE_RATIO = 0.9
FOUR_NOTE_CONTIGUOUS_CLUSTER_MIN_DURATION = 0.55
FOUR_NOTE_CONTIGUOUS_CLUSTER_MIN_SCORE_RATIO = 0.08
FOUR_NOTE_CONTIGUOUS_CLUSTER_MIN_FUNDAMENTAL_RATIO = 0.9
FOUR_NOTE_CONTIGUOUS_CLUSTER_MIN_MARGIN_RATIO = 1.15
FOUR_NOTE_GLISS_EXTENSION_MAX_DURATION = 1.0
FOUR_NOTE_GLISS_EXTENSION_SCORE_RATIO = 0.02
FOUR_NOTE_GLISS_EXTENSION_MIN_SCORE = 18.0
FOUR_NOTE_GLISS_EXTENSION_MIN_FUNDAMENTAL_RATIO = 0.82
CHORD_CLUSTER_MAX_GAP = 0.08
CHORD_CLUSTER_MAX_SINGLETON_DURATION = 0.22
CHORD_CLUSTER_MAX_TOTAL_DURATION = 1.6
REPEATED_PATTERN_LOCAL_CONTEXT_MAX_GAP = 0.35
MAX_HARMONIC_MULTIPLE = 4
SECONDARY_SCORE_RATIO = 0.12
SECONDARY_MIN_FUNDAMENTAL_RATIO = 0.18
SECONDARY_WEAK_ONSET_MIN_FUNDAMENTAL_RATIO = 0.5
SHORT_SEGMENT_SECONDARY_SCORE_RATIO = 0.06
OVERTONE_DOMINANT_FUNDAMENTAL_RATIO = 0.18
OVERTONE_DOMINANT_PENALTY_WEIGHT = 0.0
OCTAVE_ALIAS_RATIO_THRESHOLD = 1.15
OCTAVE_ALIAS_MAX_FUNDAMENTAL_RATIO = 0.34
OCTAVE_ALIAS_PENALTY = 0.85
OCTAVE_DYAD_MIN_FUNDAMENTAL_RATIO = 0.32
OCTAVE_DYAD_LOWER_OCTAVE4_MIN_FUNDAMENTAL_RATIO = 0.75
OCTAVE_DYAD_MIN_PRIMARY_ENERGY_RATIO = 0.06
OCTAVE_DYAD_UPPER_MIN_FUNDAMENTAL_RATIO = 0.95
OCTAVE_DYAD_UPPER_HARMONIC_ENERGY_RATIO = 0.05
OCTAVE_DYAD_UPPER_SCORE_RATIO = 0.03
LOW_CONFIDENCE_DYAD_MAX_DURATION = 0.25
LOW_CONFIDENCE_DYAD_MAX_SCORE = 120.0
SHORT_SECONDARY_STRIP_MAX_DURATION = 0.28
SHORT_SECONDARY_STRIP_MIN_SCORE = 60.0
SHORT_SECONDARY_STRIP_NEXT_SCORE_RATIO = 5.0
RESTART_STALE_UPPER_STRIP_MIN_INTERVAL_CENTS = 1800.0
RESTART_STALE_UPPER_STRIP_MAX_DURATION = 0.24
ADJACENT_RUN_STRIP_MIN_INTERVAL_CENTS = 80.0
ADJACENT_RUN_STRIP_MAX_INTERVAL_CENTS = 350.0
DESCENDING_STEP_HANDOFF_MAX_DURATION = 0.46
DESCENDING_ADJACENT_UPPER_CARRYOVER_MAX_DURATION = 0.24
DESCENDING_ADJACENT_UPPER_PRIMARY_ONSET_GAIN = 5.0
DESCENDING_ADJACENT_UPPER_SCORE_RATIO = 1.5
DESCENDING_RESTART_UPPER_CARRYOVER_MAX_DURATION = 0.45
DESCENDING_RESTART_UPPER_PRIMARY_ONSET_GAIN = 20.0
DESCENDING_RESTART_UPPER_SCORE_RATIO = 0.2
DESCENDING_PRIMARY_BAND_MIN_LENGTH = 4
DESCENDING_PRIMARY_SUFFIX_UPPER_CARRYOVER_MAX_DURATION = 0.45
DESCENDING_PRIMARY_BAND_PRIMARY_ONSET_GAIN = 5.0
DESCENDING_PRIMARY_SUFFIX_UPPER_SCORE_RATIO = 0.75
RESONANT_CARRYOVER_PHRASE_RESET_MIN_GAP = 0.45
RESONANT_CARRYOVER_HIGH_RETURN_MAX_DURATION = 0.24
RESONANT_CARRYOVER_HIGH_RETURN_MIN_INTERVAL_CENTS = 1800.0
RESONANT_CARRYOVER_HIGH_RETURN_MAX_NEXT_GAP = 0.12
LEADING_SINGLE_TRANSIENT_MAX_DURATION = 0.3
LEADING_SINGLE_TRANSIENT_MAX_SCORE = 150.0
LEADING_SINGLE_TRANSIENT_NEXT_SCORE_RATIO = 8.0
VERY_LOW_CONFIDENCE_EVENT_MAX_SCORE = 2.0

# Evidence gate rescue thresholds (Layer 3.5: _apply_final_decisions)
RESCUE_MIN_BACKWARD_GAIN = 10.0
RESCUE_MIN_SCORE_RATIO = 0.12
RESCUE_CARRYOVER_MIN_ONSET_GAIN = 2.0
RESCUE_CARRYOVER_MIN_SCORE_RATIO = 0.15
RESCUE_WEAK_ONSET_MIN_FUNDAMENTAL_RATIO = 0.45
RESCUE_WEAK_LOWER_MIN_FUNDAMENTAL_RATIO = 0.50
RESCUE_SCORE_FR_OVERRIDE_MIN_SCORE_RATIO = 0.15
RESCUE_SCORE_FR_OVERRIDE_MIN_FR = 0.75
BRIDGING_OCTAVE_PAIR_MAX_DURATION = 0.4
BRIDGING_OCTAVE_PAIR_MAX_SCORE = 600.0
SPLIT_UPPER_OCTAVE_PAIR_MIN_DURATION = 0.28
SPLIT_UPPER_OCTAVE_PAIR_MAX_DURATION = 0.7
SPLIT_UPPER_OCTAVE_PAIR_PRIMARY_SCORE_MAX = 800.0
SPLIT_UPPER_OCTAVE_PAIR_FRACTION = 0.45
SAME_START_PRIMARY_SINGLETON_MAX_START_DELTA = 0.02
OVERLAPPING_PRIMARY_SINGLETON_MIN_START_DELTA = 0.05
OVERLAPPING_PRIMARY_SINGLETON_MIN_OVERLAP = 0.08
OVERLAPPING_PRIMARY_SINGLETON_MAX_DURATION = 0.4

# Direct UTF-8 note labels keep the mapping readable.
PITCH_CLASS_TO_DOREMI = {
    "C": "ド",
    "C#": "ド#",
    "Db": "レb",
    "D": "レ",
    "D#": "レ#",
    "Eb": "ミb",
    "E": "ミ",
    "F": "ファ",
    "F#": "ファ#",
    "Gb": "ソb",
    "G": "ソ",
    "G#": "ソ#",
    "Ab": "ラb",
    "A": "ラ",
    "A#": "ラ#",
    "Bb": "シb",
    "B": "シ",
}

PITCH_CLASS_TO_NUMBER = {
    "C": "1",
    "C#": "#1",
    "Db": "b2",
    "D": "2",
    "D#": "#2",
    "Eb": "b3",
    "E": "3",
    "F": "4",
    "F#": "#4",
    "Gb": "b5",
    "G": "5",
    "G#": "#5",
    "Ab": "b6",
    "A": "6",
    "A#": "#6",
    "Bb": "b7",
    "B": "7",
}
